### ISSUE TITLE
Authentication Request

### ISSUE THREAD

**Issue by Obendorf96** [jasperbaes/Microsoft-Cloud-Group-Analyzer#1]
Hello Jasper,

first of all, we were very excited when we heard about your tool (https://github.com/jasperbaes/Microsoft-Cloud-Group-Analyzer) and wanted to try it out straight away.

We had been looking for this for a very long time and wanted this function.

 

The test environment has the following tools installed:

Git-2.43.0-64-bit

node-v20.11.0-x64

azure-cli-2.56.0-x64

 

We completed the first three steps of your instructions without any problems.

 

As authentication method we want to use an Azure App Registration.

 

So we followed the necessary steps:

We created an App registration and give it single tenant authentication.

We assigned all necessary permissions and granted them.

We created a new client secret and noted the Secret ID and Value.

 

Now we are stuck because we cannot find an env file in the root folder.

Can you please give us a more detailed description of this?

 

Also we couldn’t use the authentication with an admin user.

The used account is global administrator and also is user of the created enterprise application.
So what other permissions are required?

 

We would be very grateful if you could help us out here.

**Comment by nurejev** [comment]
just create a .env file in the root and paste the secret, tenant and client id. Wat i am curios about is which permission did you give.

**Comment by DR-Cloudfreunde** [comment]
Hello Jasper,

We have created an .env file with the following content:
CLIENTSECRET=dc61dd5d-b02b-4500-a68d-XXXXXXXXXXXX
TENANTID=2e96bb73-9ff7-4660-be52-XXXXXXXXXXXX
CLIENTID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

For CLIENTSECRET we used the Application (client) ID, for TENANTID we used the Directory (tenant) ID and for CLIENTID we used the Value of our Client secret (not the Secret ID).


This are the permissions we gave, because it is mentioned that all .Read.All permissions are required:

AccessReview.Read.All
Acronym.Read.All
AdministrativeUnit.Read.All
Agreement.Read.All
AgreementAcceptance.Read.All
APIConnectors.Read.All
AppCatalog.Read.All
AppCertTrustConfiguration.Read.All
Application.Read.All
AttackSimulation.Read.All
AuditLog.Read.All
AuditLogsQuery-CRM.Read.All
AuditLogsQuery-Endpoint.Read.All
AuditLogsQuery-Entra.Read.All
AuditLogsQuery-Exchange.Read.All
AuditLogsQuery-OneDrive.Read.All
AuditLogsQuery-SharePoint.Read.All
AuditLogsQuery.Read.All
AuthenticationContext.Read.All
BitlockerKey.Read.All
Bookings.Read.All
Bookmark.Read.All
BrowserSiteLists.Read.All
BusinessScenarioConfig.Read.All
ChannelMember.Read.All
ChannelMessage.Read.All
ChannelSettings.Read.All
CloudApp-Discovery.Read.All
CloudPC.Read.All
Community.Read.All
ConsentRequest.Read.All
CrossTenantUserProfileSharing.Read.All
CustomAuthenticationExtension.Read.All
CustomDetection.Read.All
CustomSecAttributeAssignment.Read.All
CustomSecAttributeAuditLogs.Read.All
CustomSecAttributeDefinition.Read.All
DelegatedAdminRelationship.Read.All
DelegatedPermissionGrant.Read.All
Device.Read.All
DeviceLocalCredential.Read.All
DeviceManagementApps.Read.All
DeviceManagementConfiguration.Read.All
DeviceManagementManagedDevices.Read.All
DeviceManagementRBAC.Read.All
DeviceManagementServiceConfig.Read.All
Directory.Read.All
DirectoryRecommendations.Read.All
Domain.Read.All
eDiscovery.Read.All
EntitlementManagement.Read.All
EventListener.Read.All
ExternalConnection.Read.All
ExternalItem.Read.All
ExternalUserProfile.Read.All
Files.Read.All
Goals-Export.Read.All
Group.Read.All
GroupMember.Read.All
IdentityProvider.Read.All
IdentityRiskEvent.Read.All
IdentityRiskyServicePrincipal.Read.All
IdentityRiskyUser.Read.All
IdentityUserFlow.Read.All
IndustryData-DataConnector.Read.All
IndustryData-InboundFlow.Read.All
IndustryData-ReferenceDefinition.Read.All
IndustryData-Run.Read.All
IndustryData-SourceSystem.Read.All
IndustryData-TimePeriod.Read.All
Insights-UserMetric.Read.All
LearningContent.Read.All
LifecycleWorkflows.Read.All
ManagedTenants.Read.All
MultiTenantOrganization.Read.All
NetworkAccess-Reports.Read.All
NetworkAccess.Read.All
NetworkAccessBranch.Read.All
NetworkAccessPolicy.Read.All
Notes.Read.All
OnlineMeetingArtifact.Read.All
OnlineMeetingRecording.Read.All
OnlineMeetingTranscript.Read.All
OnPremDirectorySynchronization.Read.All
Organization.Read.All
OrganizationalBranding.Read.All
OrgContact.Read.All
OrgSettings-AppsAndServices.Read.All
OrgSettings-DynamicsVoice.Read.All
OrgSettings-Forms.Read.All
OrgSettings-Microsoft365Install.Read.All
OrgSettings-Todo.Read.All
PartnerBilling.Read.All
PendingExternalUserProfile.Read.All
People.Read.All
PeopleSettings.Read.All
Place.Read.All
PlaceDevice.Read.All
Policy.Read.All
Presence.Read.All
PrintConnector.Read.All
Printer.Read.All
PrinterShare.Read.All
PrintJob.Read.All
PrintSettings.Read.All
ProgramControl.Read.All
QnA.Read.All
RecordsManagement.Read.All
Reports.Read.All
ReportSettings.Read.All
RoleManagement.Read.All
Schedule.Read.All
SearchConfiguration.Read.All
SecurityActions.Read.All
SecurityAlert.Read.All
SecurityAnalyzedMessage.Read.All
SecurityEvents.Read.All
SecurityIncident.Read.All
ServiceActivity-Exchange.Read.All
ServiceActivity-Microsoft365Web.Read.All
ServiceActivity-OneDrive.Read.All
ServiceActivity-Teams.Read.All
ServiceHealth.Read.All
ServiceMessage.Read.All
ServicePrincipalEndpoint.Read.All
SharePointTenantSettings.Read.All
Sites.Read.All
SubjectRightsRequest.Read.All
Subscription.Read.All
Synchronization.Read.All
TeamMember.Read.All
TeamSettings.Read.All
TeamsTab.Read.All
Teamwork.Read.All
TeamworkAppSettings.Read.All
TeamworkDevice.Read.All
TermStore.Read.All
TrustFrameworkKeySet.Read.All
User-LifeCycleInfo.Read.All
User.Read
User.Read.All
UserAuthenticationMethod.Read.All
WorkforceIntegration.Read.All

After running the script we get the following error message:

Entra ID Groups in scope:
ERROR: No user/group found for this ID. Exiting.


We get this for every test including user IDs.

For 'all' we get the following message:

 Entra ID Groups in scope:
 This can take a while...
 Progress: NaN% (0 group(s) remaining)

 ---------------------------------------------

 ERROR: you don't have permissions to read below 2 API endpoints:
[
  'https://graph.microsoft.com/v1.0/users/all',
  'https://graph.microsoft.com/v1.0/groups?$select=id'
]

Many thanks for your help

**Comment by nurejev** [comment]
following: We also give all those permissions, and everthing is setup according the docs. But Progress: 100% (0 group(s) remaining and nothing more

**Comment by jasperbaes** [comment]
Hi @Obendorf96, @DR-Cloudfreunde, @nurejev

I did not anticipate that this script would gain so much traction and interest, hence my limited effort in documentation. I've just updated the main branch. Please take a moment to review the updated setup documentation, apply it to your environment, and then test again. If you encounter any issues, please let me know. For now, I recommend using an Azure App Registration, not user authentication.

**Comment by nurejev** [comment]
@jasperbaes many thx. Got it working at one site. beautiful script. many thx. One question from the documentation. These permissions i can not find. profile and offline _ access in the Microsoft Graph

**Comment by DR-Cloudfreunde** [comment]
Hello @jasperbaes,
thank you very much for your time and for your support.
The update of the instructions helped us a lot and clarified a few things.
I would also like to thank you again for this great script. It solves so many things for us.
It is working now for us.

Hello @nurejev,
you can find these permissions only under Delegated permissions for Microsoft Graph. So we added them there and the rest under Application permissions and Delegated permissions.
